#!/bin/bash
set -v
juju-log -l WARN "Running db-relation-changed hook script"

ADDRESS=$(relation-get --app address)
if [ -z "${ADDRESS}" ]; then
    juju-log -l WARN "Address not set"
    exit 0
fi

mkdir -p /run/
kill -9 $(cat /run/pgweb.pid)
nohup /usr/local/bin/pgweb_linux_amd64 --bind=0.0.0.0 --listen=8080 --url "postgres://root@${ADDRESS}/database?sslmode=disable" > /run/pgweb.log 2>&1 < /dev/null &
echo $! > /run/pgweb.pid
