#!/bin/bash
set -v
juju-log -l WARN "Running install hook script"
status-set maintenance "Installing pgweb"

apt-get update
apt-get install -y wget unzip
wget https://github.com/sosedoff/pgweb/releases/download/v0.11.6/pgweb_linux_amd64.zip
unzip pgweb_linux_amd64.zip -d /usr/local/bin

exit 0
